-- [nfnl] after/ftplugin/fennel.fnl
local paredit = require("nvim-paredit")
vim.keymap.set("n", "'c-]'", (vim.g.maplocalleader .. "gd"), {buffer = true, remap = true})
local function _1_()
  paredit.api.move_to_parent_form_start()
  vim.cmd.normal("i() ")
  vim.cmd.normal("gqap")
  vim.fn.search("(nil)")
  vim.cmd.normal("l")
  vim.cmd.normal("diw")
  return vim.cmd.startinsert()
end
vim.keymap.set("n", "O", _1_, {buffer = true})
local function _2_()
  paredit.api.move_to_parent_form_end()
  vim.cmd.normal("a () ")
  vim.cmd.normal("gqap")
  vim.fn.search("(nil)")
  vim.cmd.normal("l")
  vim.cmd.normal("diw")
  return vim.cmd.startinsert()
end
return vim.keymap.set("n", "o", _2_, {buffer = true})
